version: '3.0'
services:
  postgres:
    container_name: postgres-container
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  postgresql:
    container_name: keycloak-postgresql-container
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    ports:
      - "5433:5433"
  keycloak:
    container_name: keycloak-container
    image: docker.io/bitnami/keycloak:19
    depends_on:
      - postgresql
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

volumes:
  postgresql_data:
    driver: local