spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/PREMIERE
    username: admin
    password: admin

keycloak:
  realm: Premiere
  auth-server-url: http://localhost:8081
  resource: premiere-keycloak
  public-client: true
  bearer-only: true