spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/PREMIERE?stringtype=unspecified
    username: admin
    password: admin

keycloak:
  realm: premiere-realm
  auth-server-url: http://localhost:8180
  resource: premiere-client
  cors: true
  credentials:
    secret: D8Bk3vIzvTYBTkZ97aHFQuYlXbqOHhSO

server:
  error:
    include-stacktrace: never