spring:
  config:
    import: secret.yaml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:postgresql://localhost:5432/PREMIERE?stringtype=unspecified
    username: admin
    password: admin

  rabbitmq:
    stomp-port: 61613
    host: localhost
    port: 5672
    username: guest
    password: guest


keycloak:
  realm: premiere-realm
  auth-server-url: http://localhost:8180
  resource: premiere-client
  cors: true


queue:
  loan-reminder-queue: loan-reminder-queue
  deposit-money-queue: deposit-money-queue

front-end:
  origin: http://localhost:3000

server:
  error:
    include-stacktrace: never

system-auth:
  private-key: MIIEpAIBAAKCAQEAmADanBNQmgK+iknNXOzZ+k7ZKqp82wArD4nE2n4Lg+6JRyGcKnHZJoYTuZ1jhC0s0HsnJn69DIeJCLlnBYgTxSYFBDQxS4bYp25+0WX7JpakibsMu6X4C9bvgDkf0QBIOY+D++u50SYM4x2yVUc1rF3V2U1YMosH5+i/SiSFvSgCiVEOGUF/IlD5S9lUUqUkvRSmFKkA4BaTO2B2sAkwLnVekN+kH2hDquado5kEGzvQQkPeB3kBvUkB9fYCeOvB3oRyxVAXLA+DYzDDl0SpWpw6NpockJTU+0fVBb/+KVCVFbclrFmF4RAPiPkPXziwsYsBRlkrkh/mV0Lug8RLGwIDAQABAoIBACfSwXN2k/1ljqoIX+dinlE36ymEdSWjS6TMgWiE8VtlWU3rflCYdz3ijrRoibQNadpNCZrKRZlMwRgqCtWmKxfRuCq7ydZxw71J86vEviIEAaOb/+ABwZTIgQLk9HL7UfDSqs+LmKk1ANdX5mr1NxirlOVToDHNvwqBLeys2OUPd7bhic+KQaM0CVNgdbqN0rNCXwbzEw3V2YkZVm5gOKko/Lj4wpHZBrOhH1aukyNdZCwgE+mhdaLFE9bAXMVTxjUoHDkpSoOd3aLp/9P499pcXwQQy1YCdtE1Rt/ldO5hIQRK3HaH7mMN2x4RXICQ/XzXEkRUC0PDkwwiJQ4BumECgYEA56ues6nPelsqklgrLXIruWTDekDWzB2IkT3hTxo9eM1Jyb6kpBZsGlmDTy9im5S2oKWWg5VgBggCtzu2QmVD2Gc4xxhUEjYibhVescSUM064gVrLzDq/yxoSUylOOn1SPU9gG9tANzD69ZMyeUP2ECyeAaxCDkKs+DFFOa7Ov1MCgYEAp/dphhrRGGg9U09CTujFUilGnGBMjiUnd9KS0Aocmd4W1CiJIkngzwtvIV6vJmMG95amX/8X5A7Pz2WWrl5gFXczjlB940+OxoJl0F6mYn6w60bcTty1Y0iIMgRWfz0YFggQWuAIU5BC7my/ilvTsqbpX7BroP70J9p4bO9WdBkCgYEA1nHOHZB6NVBeP8jNbuvX/WyAZZHPQnG0EH2vKYGolUGxo8WMsTbwKhPhsFK0fD9ULbAZewOyNuMDYIktVJhYDOC/dcvXRmRFypCNbw///t5He7WIICvhjSc8/y2k9A89KPNoi2CQOIZmRxtSBV4bTy19tR62pmyhn7w70AE373ECgYEAlb3SS4X4xyOXGIBegu6tizPVCXAoj8i7yOzniaSaHuqJu5ZvuyvVyX9OEZfR2g0KlwutQ4OtjtlNln3guY7VZg2g3s0PjejNRlfV4M+g0cpUe0vu+Dd3Vg3BraWEX2bd5DZILlvv0F+Z6+jzUavPrUN0ZqRnL15b2HPCTIuKrXECgYALvJwyYjWfhiwtRrWwFwah3nqMGKYegqNQ97KN8DFjwY5qPeTNG8doVY7BoT//z0iWGnPm2NCe1+irUql25MVOFBnJqZWZm/p1CIUuzD0RK0L8o46fDs9LJghQZDPhfE7J1j5mZDCm+4FBozj85htzEfy46dIPonZhRmosoZQFqA==
  public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmADanBNQmgK+iknNXOzZ+k7ZKqp82wArD4nE2n4Lg+6JRyGcKnHZJoYTuZ1jhC0s0HsnJn69DIeJCLlnBYgTxSYFBDQxS4bYp25+0WX7JpakibsMu6X4C9bvgDkf0QBIOY+D++u50SYM4x2yVUc1rF3V2U1YMosH5+i/SiSFvSgCiVEOGUF/IlD5S9lUUqUkvRSmFKkA4BaTO2B2sAkwLnVekN+kH2hDquado5kEGzvQQkPeB3kBvUkB9fYCeOvB3oRyxVAXLA+DYzDDl0SpWpw6NpockJTU+0fVBb/+KVCVFbclrFmF4RAPiPkPXziwsYsBRlkrkh/mV0Lug8RLGwIDAQAB
  secret-key: ucYvDUZjw1MHGGPyLLyqz36wALezGlXQhy3aFRyhjN0=
  http:
    auth-header-name: X-Auth-Token
    time-header-name: X-Auth-Time
    locale-header-name: X-Auth-Locale