spring:
  config:
    import: deployment-secret.yaml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-circular-references: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  rabbitmq:
    stomp-port: ${SPRING_RABBITMQ_STOMP_PORT}
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST}
    password: ${SPRING_RABBITMQ_PASSWORD}


keycloak:
  realm: ${KEYCLOAK_REALM}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  resource: ${KEYCLOAK_RESOURCE}
  cors: ${KEYCLOAK_CORS}

keycloak-username: ${KEYCLOAK_USERNAME}
keycloak-password: ${KEYCLOAK_PASSWORD}


queue:
  loan-reminder-queue: ${QUEUE_LOAN_REMINDER_QUEUE}
  deposit-money-queue: ${QUEUE_DEPOSIT_MONEY_QUEUE}

front-end:
  origin: ${FRONT_END_ORIGIN}
  back-up-origin: ${FRONT_END_BACK_UP_ORIGIN}

back-end:
  origin: ${BACK_END_ORIGIN}

server:
  error:
    include-stacktrace: never

system-auth:
  private-key: ${SYSTEM_AUTH_PRIVATE_KEY}
  public-key: ${SYSTEM_AUTH_PUBLIC_KEY}
  secret-key: ${SYSTEM_AUTH_SECRET_KEY}
  http:
    auth-header-name: X-Auth-Token
    time-header-name: X-Auth-Time
    locale-header-name: X-Auth-Locale

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    url: /api-docs.json

external-bank:
  secret-key: 2SIo8nL9ik
